---
- hosts: all
  sudo: yes
  vars:
    bashrc: "{{ vm.dir }}/.bashrc"
    rbenv:
      dir: "{{ vm.dir }}/.rbenv"
      shims: "{{ vm.dir }}/.rbenv/shims"
    dl:
      dir: "{{ vm.dir }}/dl"
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - common
    - storage
    - rails
