---
- name: install system gems
  gem:
    name={{ item }} state=present
    executable="{{ rbenv.shims }}/gem"
    user_install=no
  with_items:
    - rails
    - bundler
  sudo: no

- name: install app gem build-depends
  apt: name={{ item }} state=present
  # add gem dependencies to this list if needed:
  with_items:
    - libmysqlclient-dev

- name: check app gems presence
  command: "{{ rbenv.shims }}/bundler check"
  args:
    chdir: "{{ app.dir }}"
  sudo: no
  changed_when: false
  # the check errors when there's missing dependencies... ignore because we'll
  # install them later if needed
  ignore_errors: yes
  register: bundler_check
  tags:
    - bundle

- name: install app gems
  command: "{{ rbenv.shims }}/bundler install"
  args:
    chdir: "{{ app.dir }}"
  sudo: no
  when: bundler_check|failed
  tags:
    - bundle
