default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: app
  username: vagrant
  password: vagrant
  host: localhost

test:
  <<: *default
  database: saso_test

production:
  <<: *default
  database: saso
  username: saso
  password: <%= ENV['DB_PASSWORD'] %>
