---
- name: set default directory on ssh
  lineinfile:
    line="cd {{ app.dir }}" state=present
    dest="{{ bashrc }}"

- name: make ~/dl directory
  file: path="{{ dl.dir }}" state=directory
  sudo: no
