---
- name: install MySQL
  apt: name=mysql-server state=present

- name: install Ansible mysql_db depend
  apt: name=python-mysqldb state=present

- name: create app database
  mysql_db:
    name=app state=present
    collation=utf8_unicode_ci
    encoding=utf8

- name: set MySQL bind-address
  replace:
    dest=/etc/mysql/my.cnf
    regexp="^bind-address "
    replace="bind-address = 0.0.0.0"
  notify:
    - reload mysql

- name: add MySQL localhost user
  mysql_user:
    name=vagrant
    host=localhost
    password=""
    priv=*.*:ALL,GRANT
    state=present
  notify:
    - reload mysql

- name: add MySQL all hosts user
  mysql_user:
    name=vagrant
    host="%"
    password=""
    priv=*.*:ALL,GRANT
    state=present
  notify:
    - reload mysql
