---
- name: download Redis
  get_url:
    url=http://download.redis.io/redis-stable.tar.gz
    dest="{{ dl.dir }}/redis.tar.gz"
  sudo: no
  register: redis_download

- name: unzip Redis
  unarchive:
    src="{{ redis_download.dest }}" copy=no
    dest="{{ dl.dir }}"
  sudo: no
  when: redis_download.changed

- name: install Redis depend
  apt: name=tcl state=present

- name: make Redis
  command: make
  args:
    chdir: "{{ dl.dir }}/redis-stable"
  sudo: no
  when: redis_download.changed

- name: install Redis
  command: make install
  args:
    chdir: "{{ dl.dir }}/redis-stable"
    creates: /usr/local/bin/redis-server

- name: create Redis directories
  file: path={{ item }} state=directory
  with_items:
    - /etc/redis
    - /var/redis/{{ redis.port }}

- name: copy Redis init script
  template:
    src=redis-init.j2
    dest=/etc/init.d/redis_{{ redis.port }}
  register: redis_init

- name: copy Redis config
  template:
    src=redis.conf.j2
    dest=/etc/redis/{{ redis.port }}.conf
  register: redis_conf

- name: make Redis init script executable
  file: path=/etc/init.d/redis_{{ redis.port }} mode=u+x

- name: autostart Redis
  command: update-rc.d redis_{{ redis.port }} defaults
  when: redis_init.changed

- name: start Redis
  command: "{{ redis_init.dest }} start"
  when: redis_init.changed
